PREMIRRORS ??= "\
bzr://.*/.*   https://cdn.sancloud.info/file/sc-yocto/mirror/ \n \
cvs://.*/.*   https://cdn.sancloud.info/file/sc-yocto/mirror/ \n \
git://.*/.*   https://cdn.sancloud.info/file/sc-yocto/mirror/ \n \
gitsm://.*/.* https://cdn.sancloud.info/file/sc-yocto/mirror/ \n \
hg://.*/.*    https://cdn.sancloud.info/file/sc-yocto/mirror/ \n \
osc://.*/.*   https://cdn.sancloud.info/file/sc-yocto/mirror/ \n \
p4://.*/.*    https://cdn.sancloud.info/file/sc-yocto/mirror/ \n \
svn://.*/.*   https://cdn.sancloud.info/file/sc-yocto/mirror/ \n"

MIRRORS =+ "\
ftp://.*/.*      https://cdn.sancloud.info/file/sc-yocto/mirror/ \n \
http://.*/.*     https://cdn.sancloud.info/file/sc-yocto/mirror/ \n \
https://.*/.*    https://cdn.sancloud.info/file/sc-yocto/mirror/ \n"
